# -*- coding: utf-8 -*-
"""Testing_Web_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVO6X2LvfLeKnxlLV-22E-8xEOQ9dbr0

# BUILDING WEBSITE-AGENT IN 5 SIMPLE STEPS

### STEP 1: SETTING UP THE ENVIRONMENT
"""

# LOAD THE OPEN AI API KEY

"""### STEP 2: EXTRACTING TEXT FROM THE URL"""

# STEP 2: DEFINE A FUNCTION TO EXTRACT TEXT FROM URL

"""### STEP 3: CREATING THE WEBSITE Q AND A TOOL FOR THE AGENT"""



"""### STEP 4: INITIALIZING THE AGENT

### STEP 5: RUNNING THE AGENT & CHECKING THE MAGIC!
"""

# STEP 5: RUN THE AGENT
print(agent.run(" | ?"))